[build]
  functions = "netlify/functions"

[functions]
  included_files = ["cors.py", "request_helper.py"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
